livekit/ingress

- build/Dockerfile
At present curl or wget none installed in docker. That's why health checker not possible to implement. Better to have both or at least one program.
> install wget for health check

- go.mod
- go.sum
- version/version.go
This release breaks the existing ingress protocol API.
-  Update Ingress state to `failed` when we fail to start the handler (#68)
- Configure logrus to provide an output that is similar to the zap output for go-rtmp logging (#70)
- Drain active ingress when receiving SIGTERM (#71)
- Use codec constants instead of mime types (#74)
- Prevent go-rtmp panics on bad user input (#80)
- Mark the track as stereo when we have more than channel (#76)
-  Adopt psrpc Errors (#83)
- Adopt core.Fuse (#82)
-  Fail the health check while draining (#84)
- Support limiting the input framerate (#79)
- Install wget in the server container (#77)
- Add support for audio and video presets (#81)
> Ingress v0.9.0

- README.md
- version/version.go
This is the v1.0.0 release of the ingress service. This release stabilizes the API and adds support for the WHIP protocol
-  WHIP support (#97)
- Expose heath and availability on the WHIP HTTP server (#109)
- Add support for optimally bypassing transcoding when ingesting WHIP (#111)
- Set the source track information in the ingress state (#121)
- Validate IngressInfo and populate missing fields with defaults (#90)
- Fix deadlock in appsrc (#116)
- Update synchronizer and use Jitter Buffer (#118)
> Ingress version 1.0.0

- README.md
- cmd/server/main.go
- go.mod
- go.sum
- pkg/errors/errors.go
- pkg/media/pipeline.go
- pkg/media/whip/whipsrc.go
- pkg/params/params.go
- pkg/rtmp/relay_handler.go
- pkg/rtmp/server.go
- pkg/service/process_manager.go
- pkg/service/service.go
- pkg/service/session_manager.go
- pkg/whip/whip_handler.go
This generates a resourceID for rtmp sessions as well, and uses it to differentiate the different sessions, even if they belong to the same ingress.
This also make sure the ingress session terminates properly if the participant gets removed from the room (because another one if the same participant id joined, for instance).
This should prevent 2 ingress with the same ID to be started at the same time, even if they end up being handled by a different ingress server, as the room logic will terminate the older one of the 2 sessions. There is already explicit logic to terminate any active ingress session if the ingress gets modified to change the participant_id.
> Handle better the case where 2 publishers with the same ingress ID connect to the same ingress instance

- pkg/service/service.go
- pkg/whip/whip_track_handler.go
This should limit jitter on the reader routine since the writer blocks on the local participant reader, which operates off a ticker.
> Split the whip writer in a separate goroutine

- go.mod
- pkg/errors/errors.go
- pkg/media/urlpull/source.go
- pkg/media/whip/appsrc.go
- pkg/whip/sdk_media_sink.go
- pkg/whip/whip_track_handler.go
This seems needed to support HLS on linux.
> Add video/mpegts to the list of supported url pull media types

- pkg/stats/monitor.go
This makes sure we keep some CPU idle in our load target when deciding whether to accept a new request, and a breakage in the logic.
> Fix CanAccept logic

- pkg/media/output.go
This PR makes sure that we do not cut up to ~300ms at the end of url ingress by draining the output channel.
> Drain output channel on EOS

- cmd/server/main.go
- pkg/errors/errors.go
- pkg/media/rtmp/appsrc.go
- pkg/media/whip/whipsrc.go
- pkg/params/params.go
- pkg/rtmp/relay_handler.go
- pkg/rtmp/server.go
- pkg/service/handler.go
- pkg/service/process_manager.go
- pkg/service/relay.go
- pkg/service/service.go
- pkg/whip/relay_handler.go
- pkg/whip/server.go
- pkg/whip/whip_handler.go
Also only bind the relay to localhost
> Use a secret token to authenticate relay connections

- go.mod
- go.sum
renovate doesn't seem to update imports (appending v2) after a major version update.
> Revert failed renovate update

- pkg/errors/errors.go
- pkg/media/input.go
- pkg/media/urlpull/source.go
This allows restreaming SRT streams published by another server.
> Add support for SRT in URL Pull ingress

- pkg/lksdk_output/lksdk_output.go
- pkg/media/output.go
- pkg/media/webrtc_sink.go
- pkg/whip/sdk_media_sink.go
Caling WriteSample directly on the local track makes dealing with disconnections and A/V sync easier.
WriteSample succeeds even if the PeerConnection is disconnected. This means that the output lost packet count gathered by the service is inaccurate.
> Do not use sample providers in the go SDK

- pkg/media/output.go
- pkg/media/pipeline.go
- pkg/media/webrtc_sink.go
Drop media while waiting for connection, after the decoder to avoid having to wait for a key frame once dropping stops.
This prevents media from accumulating in the pipeline while waiting for the room connection.
> Connect to room asynchronously

- pkg/whip/server.go
Also make it explicit that Trickle ICE is not supported.
> Do not log errors triggered by bad input as warning

- version/version.go
- Log WHIP user agent and RTP packet if unmarshalling fails (#274)
- Tear down full WHIP session of one of the track handlers fail (#277)
- nil check on SDK teardown (#278)
- Be sure to cancel input initialization when shutting down an ingress during start up (#279)
- Update module golang.org/x/image to v0.18.0 [SECURITY] (#286)
- Implement KillIngressSession rpc (#282)
- Report failure when WHIP handler fails to initialize (#285)
- Stop output sdk watchdog on teardown (#287)
- Update go-gst (#305)
- Update to pion/webrtc v4 (#312)
> Version 1.4.3

- .github/workflows/build.yaml
As in https://github.com/livekit/sip/pull/275, the usage of actions/cache here is not really doing anything - proposing removing.
> Remove actions/cache usage in workflows/build.yaml

- pkg/service/service.go
Make sure to initialize the ingress state for URL ingresses that are created directly by the Ingress server
> Initialize URL ingress with BUFFERING status

- cmd/server/main.go
- pkg/lksdk_output/lksdk_output.go
- pkg/lksdk_output/media_watchdog.go
- pkg/lksdk_output/media_watchdog_test.go
- pkg/lksdk_output/track_watchdog.go
- pkg/media/output.go
- pkg/media/webrtc_sink.go
- pkg/whip/sdk_media_sink.go
This adds a media watchdog at the input of the go SDK (so at the tail of the pipeline). This is needed because in some cases, such as SRT input. gstreamer will retry to connect for ever without emitting any event about the failure to connect. This will close the ingress if no media is received on any track for 1 min.
> Add a media watchdog

- pkg/lksdk_output/lksdk_output.go
- pkg/media/output.go
- pkg/media/webrtc_sink.go
- pkg/params/params.go
- pkg/utils/blocking_queue.go
- pkg/utils/output_synchronizer.go
- pkg/whip/sdk_media_sink.go
Currently, the output synchronizer increases the reference/wait time if a packet arrives later than expected at the output to compensate drifts, stalls or other processing hiccups. The reference time is however never brought back down if the clock drifts the other way, or the total pipeline processing time decreases. In the case of SRT where there is a guaranteed latency between client and server, this can cause the input buffer to fill up to its max value, causing essentially a deadlock. 
This patch adds a queue we can monitor between the appsink and the go SDK. We measure the length of this queue and if it grows to more than 2 buffers, we decrease the synchronizer wait time in quantum of 10ms until the queue shortens below the threshold. 
The above is disabled to HLS as for VOD (or live …
> back down synchronizer wait time if the processing pipeline becomes too long

- pkg/errors/errors.go
Update misspelled `disonnected` to `disconnected`
> Fix typo in error messages
